export type SupportedLocale = 'pt-BR' | 'en';
export type LanguagePreference = 'auto' | SupportedLocale;

export const en = {
  'common.active': 'Active',
  'common.none': 'None',
  'common.unknown': 'Unknown',
  'common.cancelled': 'Operation cancelled.',
  'common.cancel': 'Cancel',
  'common.submit': 'Continue',
  'common.invalidForm': 'Review the required fields and allowed values.',
  'common.noWorkspace': 'Open a workspace in VS Code to use this action.',
  'common.error': 'Operation failed: {message}',
  'common.yesLocal': 'Yes (Local Test Environment)',
  'common.noRemote': 'No (Remote Production)',
  'section.overview': 'Overview',
  'section.sdd': 'SDD & Planning',
  'section.core': 'Core & Releases',
  'section.projects': 'Projects & Test Environment',
  'section.diagnostics': 'Environment & Diagnostics',
  'section.agents': 'Agents, Documentation & Settings',
  'section.custom': 'Project Actions',
  'overview.scope': 'SDD Scope: {scope}',
  'overview.target': 'Target Project: {target}',
  'overview.noTarget': 'Target Project: not selected',
  'overview.language': 'Extension Language: {language}',
  'overview.autonomy': 'Autonomy: {mode}',
  'sdd.selectScope': 'Select SDD Scope',
  'sdd.viewMode': 'Markdown Display: {mode}',
  'sdd.openCurrent': 'Open CURRENT.md',
  'sdd.openSpec': 'Open SPEC.md',
  'sdd.openChecklist': 'Open Validation Checklist',
  'sdd.browseRequests': 'Browse Human Requests',
  'sdd.browseBatches': 'Browse Implementation Batches',
  'sdd.browseBacklog': 'Browse Backlog',
  'sdd.browseDecisions': 'Browse Architecture Decisions',
  'sdd.browseHandoffs': 'Browse Agent Handoffs',
  'sdd.autoGardening': 'Memory monitoring: {status}',
  'sdd.runGardening': 'Run Memory Gardening',
  'sdd.createGardening': 'Create Gardening Request',
  'sdd.scopePrompt': 'Select the SDD repository scope:',
  'sdd.scopeChanged': 'SDD scope: {scope}',
  'sdd.folderMissing': 'The SDD folder was not found for {scope}.',
  'sdd.fileMissing': 'Document not found: {path} ({scope})',
  'core.updateAll': 'Update Core System',
  'core.syncResources': 'Sync Resources',
  'core.cssRebuild': 'Rebuild CSS for {target}',
  'core.cssAudit': 'Audit CSS for {target}',
  'release.verify': 'Verify Release Permission',
  'release.productManager': 'Gestor',
  'release.productInstaller': 'Gestor Installer',
  'release.manager': 'Create Gestor Release',
  'release.installer': 'Create Gestor Installer Release',
  'release.permissionAllowed': 'Release permission: {permission}',
  'release.permissionDenied': 'Release actions are unavailable with GitHub permission {permission}.',
  'release.permissionUnknown': 'Release permission could not be verified: {reason}',
  'release.preflightFailed': 'Release preflight failed: {reason}',
  'release.selectType': 'Select the release increment:',
  'release.selectMode': 'Select the official release mode:',
  'release.tagMessage': 'Annotated tag summary',
  'release.commitMessage': 'Release commit message',
  'release.confirm': 'Run {product} release {current} → {next} ({tag}) using {mode}?',
  'release.started': '{product} release started in a dedicated task.',
  'release.openActions': 'Open GitHub Actions',
  'release.formTitle': 'Create {product} Release',
  'release.formDescription': 'Review the computed version and provide the release messages in this single form.',
  'release.impact': 'Remote operation: creates a commit and tag and may publish through GitHub Actions.',
  'release.currentVersion': 'Current version',
  'release.nextVersion': 'Next version',
  'release.tag': 'Release tag',
  'release.command': 'Official command',
  'release.type': 'Version increment',
  'release.mode': 'Release mode',
  'release.modeAutomatic': 'Automatic — push tag and let GitHub Actions publish',
  'release.modeManual': 'Manual — publish with GitHub CLI',
  'release.workflow': 'Affected workflow: {workflow}',
  'release.permissionChecking': 'Checking GitHub authentication and release permission…',
  'release.cleanRequired': 'The Core working tree must be clean before a release.',
  'release.tagExists': 'The tag {tag} already exists.',
  'projects.setTarget': 'Select Target Project',
  'projects.updateAll': 'Update Target Project [{target}]',
  'projects.deploy': 'Deploy Target Project [{target}]',
  'projects.syncCore': 'Sync Core → Project [{target}]',
  'projects.syncFiles': 'Sync Files → Test Environment [{target}]',
  'projects.updateSelect': 'Update Another Project…',
  'projects.deploySelect': 'Deploy Another Project…',
  'projects.scaffold': 'Create Satellite Project',
  'projects.register': 'Register Existing Project',
  'projects.clone': 'Clone Missing Repositories',
  'projects.syncTemplate': 'Sync Environment Template',
  'projects.noTargetWarning': 'Select a valid target project before running this action.',
  'projects.selectPrompt': 'Select a project:',
  'projects.targetPrompt': 'Select the default target project:',
  'projects.targetChanged': 'Target project: {target}',
  'projects.environmentMissing': 'The active environment.json was not found.',
  'projects.templateMissing': 'The environment.json template was not found.',
  'projects.idPrompt': 'Unique project identifier (lowercase slug):',
  'projects.namePrompt': 'Project display name:',
  'projects.urlPrompt': 'Project base URL:',
  'projects.localPrompt': 'Does the project run in the local Docker environment?',
  'projects.saved': 'Project {name} ({id}) was registered in environment.json.',
  'projects.scaffolded': 'Satellite project {name} ({id}) was created.',
  'projects.syncSucceeded': 'The active environment was synchronized with the template.',
  'projects.githubOwnerPrompt': 'GitHub organization or owner for the Conn2Flow repositories:',
  'projects.clonePrompt': 'Select an official repository to clone:',
  'projects.allPresent': 'All configured repositories are present beside the workspace.',
  'projects.missingRepositories': 'Missing repositories: {names}.',
  'diagnostics.dockerStatus': 'Docker Container Status',
  'diagnostics.apacheLogs': 'Follow Apache Logs',
  'diagnostics.phpLogs': 'Follow PHP Logs',
  'diagnostics.truncatePhp': 'Clear PHP Error Log',
  'diagnostics.aiSync': 'Validate and Sync Skills',
  'diagnostics.syncAll': 'Distribute Skills to Repositories',
  'agents.selectMode': 'Select Agent Topology or Autonomy',
  'agents.launchClaude': 'Start Claude Code (/goal)',
  'agents.copyPrompt': 'Copy Executor Prompt',
  'agents.recordHandoff': 'Open Current Handoff',
  'agents.prepareReview': 'Prepare Architect Review',
  'agents.reviewReady': 'Handoff opened and Source Control focused. Review and publish manually when ready.',
  'agents.activeMissing': 'The active request was not found in sdd/human-requests/CURRENT.md.',
  'agents.promptCopied': 'Executor prompt copied to the clipboard.',
  'agents.handoffOpened': 'The current handoff was opened for editing.',
  'agents.launchPrompt': 'How should Claude Code be started?',
  'agents.copyOption': 'Copy prompt for the Claude extension',
  'agents.cliOption': 'Run Claude CLI in a task',
  'agents.npxOption': 'Run with NPX',
  'agents.installOption': 'Install Claude CLI globally',
  'agents.started': 'Claude Code started for {request}.',
  'agents.goalInstruction': '/goal Read the active brief in sdd/human-requests/CURRENT.md ({request}), complete its Live Todo List under SDD governance, validate locally, update the validation checklist and current handoff. Do not commit, push, deploy or release without explicit human authorization.',
  'agents.executorPrompt': 'You are the Conn2Flow SDD Executor. Implement the approved active request [{request}], maintain its Live Todo List, validate locally and record evidence in the validation checklist and current handoff. Never use broad Git staging, never copy files manually into test mirrors, and never commit, push, deploy or release without explicit human authorization.\n\nACTIVE REQUEST ({request})\n\n{content}',
  'docs.panel': 'Dev Tools Panel Manual',
  'docs.marketplace': 'VS Code Marketplace Publication Guide',
  'docs.cli': 'CLI and MCP Quick Guide',
  'docs.orchestration': 'Multi-Agent Orchestration Playbook',
  'docs.architecture': 'Dual-Agent Architecture',
  'docs.skills': 'Skills Catalog',
  'settings.language': 'Select Extension Language',
  'settings.terminal': 'Terminal Mode: {mode}',
  'language.auto': 'Automatic (VS Code)',
  'language.pt-BR': 'Português (Brasil)',
  'language.en': 'English',
  'language.changed': 'Extension language changed to {language}.',
  'language.reload': 'Reload Window may be required to translate Command Palette entries.',
  'terminal.reuse': 'Reuse dedicated terminal',
  'terminal.new': 'Create a new terminal per command',
  'command.confirm': 'Run “{label}” for {target}?',
  'command.confirmButton': 'Run',
  'command.formTitle': 'Confirm {label}',
  'command.impact': 'Impact classification: {impact}',
  'command.target': 'Target',
  'command.command': 'Command',
  'command.acknowledge': 'I reviewed the target and command',
  'command.trustRequired': 'Trust this workspace before running Conn2Flow commands.',
  'command.started': '{label} started.',
  'command.succeeded': '{label} completed successfully.',
  'command.failed': '{label} failed with exit code {code}.',
  'command.busy': 'Another exclusive Conn2Flow pipeline is already running.',
  'custom.edit': 'Edit Project Actions',
  'custom.trustRequired': 'Custom project actions are disabled in an untrusted workspace.',
  'custom.created': 'The .c2f/actions.json manifest was created and opened for editing.',
  'backlog.all': 'All statuses',
  'backlog.filterPrompt': 'Filter backlog items by status:',
  'backlog.itemPrompt': '[{scope}] Select a backlog item:',
  'backlog.empty': 'No backlog items were found for {scope}.',
  'backlog.drift': 'Status drift: index={index}, file={file}',
  'backlog.openIndex': 'Open BACKLOG-INDEX.md',
  'backlog.promote': 'Promote Backlog Item to Request',
  'backlog.intakeGate': 'Promotion requires an explicit governed SDD request. No implementation will start automatically.',
  'backlog.promotionDraft': 'Create a governed request draft for {id}?',
  'backlog.promotionPrompt': 'Prepare a governed SDD request for backlog item {id}.\nType: {type}\nStatus: {status}\nTitle: {title}\nNext action: {action}\nSource: sdd/backlog/{file}\n\nUse start-sdd-slice. Do not implement until the new request is explicitly approved.',
  'sdd.noFiles': 'No Markdown files were found in {directory} for {scope}.',
  'sdd.selectFile': '[{scope}] Select a file from {title}:',
  'sdd.currentFile': 'Active request',
  'logs.apacheStarted': 'Following Apache logs.',
  'logs.apacheStopped': 'Apache log follow stopped.',
  'logs.phpStarted': 'Following PHP logs.',
  'logs.phpStopped': 'PHP log follow stopped.',
  'mode.supervised': 'Supervised',
  'mode.monitored': 'Autonomous Monitored',
  'mode.headless': 'Autonomous Headless',
  'mode.triad': 'Agent Triad',
  'mode.dual': 'Dual Agent',
  'view.preview': 'Rendered Preview',
  'view.code': 'Source Code',
  'view.both': 'Side by Side',
  'gardening.enabled': 'enabled',
  'gardening.disabled': 'disabled',
  'status.sddTooltip': 'Open the active SDD request',
  'status.modesTooltip': 'Change agent topology or autonomy',
  'status.dockerTooltip': 'Inspect active Docker containers'
} as const;

export type TranslationKey = keyof typeof en;

export const ptBR: Record<TranslationKey, string> = {
  'common.active': 'Ativo',
  'common.none': 'Nenhum',
  'common.unknown': 'Desconhecido',
  'common.cancelled': 'Operação cancelada.',
  'common.cancel': 'Cancelar',
  'common.submit': 'Continuar',
  'common.invalidForm': 'Revise os campos obrigatórios e os valores permitidos.',
  'common.noWorkspace': 'Abra um workspace no VS Code para usar esta ação.',
  'common.error': 'Falha na operação: {message}',
  'common.yesLocal': 'Sim (Ambiente de Testes Local)',
  'common.noRemote': 'Não (Produção Remota)',
  'section.overview': 'Visão Geral',
  'section.sdd': 'SDD & Planejamento',
  'section.core': 'Core & Releases',
  'section.projects': 'Projetos & Ambiente de Testes',
  'section.diagnostics': 'Ambiente & Diagnóstico',
  'section.agents': 'Agentes, Documentação & Configurações',
  'section.custom': 'Ações do Projeto',
  'overview.scope': 'Escopo SDD: {scope}',
  'overview.target': 'Projeto Alvo: {target}',
  'overview.noTarget': 'Projeto Alvo: não selecionado',
  'overview.language': 'Idioma da Extensão: {language}',
  'overview.autonomy': 'Autonomia: {mode}',
  'sdd.selectScope': 'Selecionar Escopo SDD',
  'sdd.viewMode': 'Exibição Markdown: {mode}',
  'sdd.openCurrent': 'Abrir CURRENT.md',
  'sdd.openSpec': 'Abrir SPEC.md',
  'sdd.openChecklist': 'Abrir Checklist de Validação',
  'sdd.browseRequests': 'Navegar Requisições Humanas',
  'sdd.browseBatches': 'Navegar Lotes de Implementação',
  'sdd.browseBacklog': 'Navegar Backlog',
  'sdd.browseDecisions': 'Navegar Decisões Arquiteturais',
  'sdd.browseHandoffs': 'Navegar Handoffs de Agentes',
  'sdd.autoGardening': 'Monitoramento de memória: {status}',
  'sdd.runGardening': 'Executar Memory Gardening',
  'sdd.createGardening': 'Criar Requisição de Gardening',
  'sdd.scopePrompt': 'Selecione o repositório do escopo SDD:',
  'sdd.scopeChanged': 'Escopo SDD: {scope}',
  'sdd.folderMissing': 'A pasta SDD não foi encontrada para {scope}.',
  'sdd.fileMissing': 'Documento não encontrado: {path} ({scope})',
  'core.updateAll': 'Atualizar Sistema Core',
  'core.syncResources': 'Sincronizar Recursos',
  'core.cssRebuild': 'Reconstruir CSS de {target}',
  'core.cssAudit': 'Auditar CSS de {target}',
  'release.verify': 'Verificar Permissão de Release',
  'release.productManager': 'Gestor',
  'release.productInstaller': 'Gestor Instalador',
  'release.manager': 'Criar Release do Gestor',
  'release.installer': 'Criar Release do Gestor Instalador',
  'release.permissionAllowed': 'Permissão de release: {permission}',
  'release.permissionDenied': 'As ações de release não estão disponíveis com a permissão GitHub {permission}.',
  'release.permissionUnknown': 'Não foi possível verificar a permissão de release: {reason}',
  'release.preflightFailed': 'O preflight de release falhou: {reason}',
  'release.selectType': 'Selecione o incremento do release:',
  'release.selectMode': 'Selecione o modo oficial de release:',
  'release.tagMessage': 'Resumo da tag anotada',
  'release.commitMessage': 'Mensagem do commit de release',
  'release.confirm': 'Executar release de {product} {current} → {next} ({tag}) no modo {mode}?',
  'release.started': 'Release de {product} iniciado em uma tarefa dedicada.',
  'release.openActions': 'Abrir GitHub Actions',
  'release.formTitle': 'Criar Release do {product}',
  'release.formDescription': 'Revise a versão calculada e informe as mensagens do release neste único formulário.',
  'release.impact': 'Operação remota: cria commit e tag e pode publicar pelo GitHub Actions.',
  'release.currentVersion': 'Versão atual',
  'release.nextVersion': 'Próxima versão',
  'release.tag': 'Tag do release',
  'release.command': 'Comando oficial',
  'release.type': 'Incremento de versão',
  'release.mode': 'Modo de release',
  'release.modeAutomatic': 'Automático — envia a tag e deixa o GitHub Actions publicar',
  'release.modeManual': 'Manual — publica usando GitHub CLI',
  'release.workflow': 'Workflow afetado: {workflow}',
  'release.permissionChecking': 'Verificando autenticação GitHub e permissão de release…',
  'release.cleanRequired': 'A árvore de trabalho do Core deve estar limpa antes de um release.',
  'release.tagExists': 'A tag {tag} já existe.',
  'projects.setTarget': 'Selecionar Projeto Alvo',
  'projects.updateAll': 'Atualizar Projeto Alvo [{target}]',
  'projects.deploy': 'Deploy do Projeto Alvo [{target}]',
  'projects.syncCore': 'Sincronizar Core → Projeto [{target}]',
  'projects.syncFiles': 'Sincronizar Arquivos → Ambiente de Testes [{target}]',
  'projects.updateSelect': 'Atualizar Outro Projeto…',
  'projects.deploySelect': 'Deploy de Outro Projeto…',
  'projects.scaffold': 'Criar Projeto Satélite',
  'projects.register': 'Cadastrar Projeto Existente',
  'projects.clone': 'Clonar Repositórios Ausentes',
  'projects.syncTemplate': 'Sincronizar Template do Environment',
  'projects.noTargetWarning': 'Selecione um projeto alvo válido antes de executar esta ação.',
  'projects.selectPrompt': 'Selecione um projeto:',
  'projects.targetPrompt': 'Selecione o projeto alvo padrão:',
  'projects.targetChanged': 'Projeto alvo: {target}',
  'projects.environmentMissing': 'O environment.json ativo não foi encontrado.',
  'projects.templateMissing': 'O template de environment.json não foi encontrado.',
  'projects.idPrompt': 'Identificador único do projeto (slug em minúsculas):',
  'projects.namePrompt': 'Nome de exibição do projeto:',
  'projects.urlPrompt': 'URL base do projeto:',
  'projects.localPrompt': 'O projeto roda no ambiente local Docker?',
  'projects.saved': 'Projeto {name} ({id}) cadastrado no environment.json.',
  'projects.scaffolded': 'Projeto satélite {name} ({id}) criado.',
  'projects.syncSucceeded': 'O environment ativo foi sincronizado com o template.',
  'projects.githubOwnerPrompt': 'Organização ou owner GitHub dos repositórios Conn2Flow:',
  'projects.clonePrompt': 'Selecione um repositório oficial para clonar:',
  'projects.allPresent': 'Todos os repositórios configurados estão presentes ao lado do workspace.',
  'projects.missingRepositories': 'Repositórios ausentes: {names}.',
  'diagnostics.dockerStatus': 'Status dos Containers Docker',
  'diagnostics.apacheLogs': 'Acompanhar Logs Apache',
  'diagnostics.phpLogs': 'Acompanhar Logs PHP',
  'diagnostics.truncatePhp': 'Limpar Log de Erros PHP',
  'diagnostics.aiSync': 'Validar e Sincronizar Skills',
  'diagnostics.syncAll': 'Distribuir Skills para Repositórios',
  'agents.selectMode': 'Selecionar Topologia ou Autonomia',
  'agents.launchClaude': 'Iniciar Claude Code (/goal)',
  'agents.copyPrompt': 'Copiar Prompt do Executor',
  'agents.recordHandoff': 'Abrir Handoff Atual',
  'agents.prepareReview': 'Preparar Revisão do Arquiteto',
  'agents.reviewReady': 'Handoff aberto e Controle de Código-Fonte em foco. Revise e publique manualmente quando estiver pronto.',
  'agents.activeMissing': 'A requisição ativa não foi encontrada em sdd/human-requests/CURRENT.md.',
  'agents.promptCopied': 'Prompt do executor copiado para a área de transferência.',
  'agents.handoffOpened': 'O handoff atual foi aberto para edição.',
  'agents.launchPrompt': 'Como o Claude Code deve ser iniciado?',
  'agents.copyOption': 'Copiar prompt para a extensão do Claude',
  'agents.cliOption': 'Executar Claude CLI em uma tarefa',
  'agents.npxOption': 'Executar via NPX',
  'agents.installOption': 'Instalar Claude CLI globalmente',
  'agents.started': 'Claude Code iniciado para {request}.',
  'agents.goalInstruction': '/goal Leia o briefing ativo em sdd/human-requests/CURRENT.md ({request}), conclua a Live Todo List sob governança SDD, valide localmente e atualize o checklist de validação e o handoff atual. Não execute commit, push, deploy ou release sem autorização humana explícita.',
  'agents.executorPrompt': 'Você é o Executor SDD do Conn2Flow. Implemente a requisição ativa aprovada [{request}], mantenha a Live Todo List, valide localmente e registre evidências no checklist de validação e no handoff atual. Nunca use staging Git amplo, nunca copie arquivos manualmente para espelhos de teste e nunca execute commit, push, deploy ou release sem autorização humana explícita.\n\nREQUISIÇÃO ATIVA ({request})\n\n{content}',
  'docs.panel': 'Manual do Painel Dev Tools',
  'docs.marketplace': 'Guia de Publicação no Marketplace VS Code',
  'docs.cli': 'Guia Rápido de CLI e MCP',
  'docs.orchestration': 'Playbook de Orquestração Multi-Agentes',
  'docs.architecture': 'Arquitetura de Agente Duplo',
  'docs.skills': 'Catálogo de Skills',
  'settings.language': 'Selecionar Idioma da Extensão',
  'settings.terminal': 'Modo de Terminal: {mode}',
  'language.auto': 'Automático (VS Code)',
  'language.pt-BR': 'Português (Brasil)',
  'language.en': 'English',
  'language.changed': 'Idioma da extensão alterado para {language}.',
  'language.reload': 'Pode ser necessário recarregar a janela para traduzir entradas da Paleta de Comandos.',
  'terminal.reuse': 'Reutilizar terminal dedicado',
  'terminal.new': 'Criar novo terminal por comando',
  'command.confirm': 'Executar “{label}” para {target}?',
  'command.confirmButton': 'Executar',
  'command.formTitle': 'Confirmar {label}',
  'command.impact': 'Classificação de impacto: {impact}',
  'command.target': 'Alvo',
  'command.command': 'Comando',
  'command.acknowledge': 'Revisei o alvo e o comando',
  'command.trustRequired': 'Confie neste workspace antes de executar comandos Conn2Flow.',
  'command.started': '{label} iniciado.',
  'command.succeeded': '{label} concluído com sucesso.',
  'command.failed': '{label} falhou com código de saída {code}.',
  'command.busy': 'Outro pipeline exclusivo do Conn2Flow já está em execução.',
  'custom.edit': 'Editar Ações do Projeto',
  'custom.trustRequired': 'Ações personalizadas estão desativadas em workspace não confiável.',
  'custom.created': 'O manifesto .c2f/actions.json foi criado e aberto para edição.',
  'backlog.all': 'Todos os status',
  'backlog.filterPrompt': 'Filtre os itens de backlog por status:',
  'backlog.itemPrompt': '[{scope}] Selecione um item do backlog:',
  'backlog.empty': 'Nenhum item de backlog foi encontrado para {scope}.',
  'backlog.drift': 'Divergência de status: índice={index}, arquivo={file}',
  'backlog.openIndex': 'Abrir BACKLOG-INDEX.md',
  'backlog.promote': 'Promover Item do Backlog para Requisição',
  'backlog.intakeGate': 'A promoção exige uma requisição SDD governada e explícita. Nenhuma implementação será iniciada automaticamente.',
  'backlog.promotionDraft': 'Criar um rascunho governado de requisição para {id}?',
  'backlog.promotionPrompt': 'Prepare uma requisição SDD governada para o item de backlog {id}.\nTipo: {type}\nStatus: {status}\nTítulo: {title}\nPróxima ação: {action}\nFonte: sdd/backlog/{file}\n\nUse start-sdd-slice. Não implemente até a nova requisição ser aprovada explicitamente.',
  'sdd.noFiles': 'Nenhum arquivo Markdown foi encontrado em {directory} para {scope}.',
  'sdd.selectFile': '[{scope}] Selecione um arquivo de {title}:',
  'sdd.currentFile': 'Requisição ativa',
  'logs.apacheStarted': 'Acompanhando logs Apache.',
  'logs.apacheStopped': 'Acompanhamento de logs Apache encerrado.',
  'logs.phpStarted': 'Acompanhando logs PHP.',
  'logs.phpStopped': 'Acompanhamento de logs PHP encerrado.',
  'mode.supervised': 'Supervisionado',
  'mode.monitored': 'Autônomo Monitorado',
  'mode.headless': 'Autônomo Headless',
  'mode.triad': 'Tríade de Agentes',
  'mode.dual': 'Duplo Agente',
  'view.preview': 'Preview Renderizado',
  'view.code': 'Código-Fonte',
  'view.both': 'Lado a Lado',
  'gardening.enabled': 'ativado',
  'gardening.disabled': 'desativado',
  'status.sddTooltip': 'Abrir a requisição SDD ativa',
  'status.modesTooltip': 'Alterar topologia de agentes ou autonomia',
  'status.dockerTooltip': 'Inspecionar containers Docker ativos'
};

export function resolveLocale(
  preference: LanguagePreference,
  vscodeLanguage: string,
  environmentLanguage?: string
): SupportedLocale {
  if (preference === 'pt-BR' || preference === 'en') {
    return preference;
  }

  const normalizedVscode = vscodeLanguage.trim().toLocaleLowerCase('en-US');
  if (normalizedVscode === 'pt' || normalizedVscode.startsWith('pt-')) {
    return 'pt-BR';
  }
  if (normalizedVscode === 'en' || normalizedVscode.startsWith('en-')) {
    return 'en';
  }

  const normalizedEnvironment = (environmentLanguage || '').trim().toLocaleLowerCase('en-US');
  if (normalizedEnvironment === 'pt' || normalizedEnvironment === 'pt-br') {
    return 'pt-BR';
  }
  return 'en';
}

export function translate(
  locale: SupportedLocale,
  key: TranslationKey,
  values: Readonly<Record<string, string | number | boolean>> = {}
): string {
  const catalog = locale === 'pt-BR' ? ptBR : en;
  return catalog[key].replace(/\{([a-zA-Z0-9_]+)\}/g, (match, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : match
  );
}
