export type SupportedLocale = 'pt-BR' | 'en';
export type LanguagePreference = 'auto' | SupportedLocale;

export const en = {
  'common.active': 'Active',
  'common.none': 'None',
  'common.unknown': 'Unknown',
  'common.cancelled': 'Operation cancelled.',
  'common.cancel': 'Cancel',
  'common.submit': 'Continue',
  'common.invalidForm': 'Review the required fields and allowed values.',
  'common.noWorkspace': 'Open a workspace in VS Code to use this action.',
  'common.error': 'Operation failed: {message}',
  'common.yesLocal': 'Yes (Local Test Environment)',
  'common.noRemote': 'No (Remote Production)',
  'section.overview': '🎛️ Main Controls',
  'section.sdd': '📐 SDD & Planning',
  'section.core': '⚡ Core & Releases',
  'section.projects': '📁 Projects & Test Environment',
  'section.diagnostics': '🩺 Environment & Diagnostics',
  'section.agents': '📚 Documentation & Settings',
  'section.custom': '🧩 Project Actions',
  'tooltip.section.overview': 'Set the SDD scope, target project, interface language, agent mode, and watcher state before running work. These choices are persisted for the current workspace.',
  'tooltip.section.sdd': 'Browse the governed SDD records and coordinate executor work from the active scope. Opening documents never changes their contents.',
  'tooltip.section.core': 'Run Core maintenance and prepare guarded releases. Release execution stays locked until its preflight gates pass.',
  'tooltip.section.projects': 'Select and operate a satellite project in the local test environment. Commands use the selected target explicitly.',
  'tooltip.section.diagnostics': 'Inspect local services, logs, and AI-kit consistency while diagnosing the development environment. Log follow can be stopped from the same control.',
  'tooltip.section.agents': 'Open the operational manuals for the Dev Tools, CLI, SDD workflow, agent architecture, and skills. These links are read-only navigation aids.',
  'tooltip.section.custom': 'Run project-defined actions from the local manifest. Commands remain unavailable until the workspace is trusted.',
  'overview.scope': '🎯 SDD Scope: {scope}',
  'overview.target': '📌 Target Project: {target}',
  'overview.noTarget': '📌 Target Project: not selected',
  'overview.language': '🌐 Extension Language: {language}',
  'overview.topology': '👥 Topology: {mode}',
  'overview.autonomy': '🛡️ Autonomy: {mode}',
  'tooltip.overview.scope': 'Choose which repository SDD directory the panel reads. Use it before opening requests or validation records to avoid acting on another project.',
  'tooltip.overview.target': 'Change the explicit project target for contextual project commands. It does not run an update or deploy by itself.',
  'tooltip.overview.noTarget': 'Choose a project before using contextual project actions. No project pipeline will run until a valid target is selected.',
  'tooltip.overview.language': 'Choose the runtime language for panel labels and forms. Static Command Palette titles may require a VS Code reload.',
  'tooltip.overview.topology': 'Choose the dual-agent or triad collaboration model. The selection shapes generated agent prompts for this workspace.',
  'tooltip.overview.autonomy': 'Choose the supervised, monitored, or headless working mode. The selected mode is passed to the governed agent workflow.',
  'sdd.selectScope': '🎯 Select SDD Scope',
  'sdd.viewMode': '👁️ Markdown Display: {mode}',
  'sdd.openCurrent': '📋 Open CURRENT.md',
  'sdd.openSpec': '📜 Open SPEC.md',
  'sdd.openChecklist': '✅ Open Validation Checklist',
  'sdd.browseRequests': '📥 Browse Human Requests',
  'sdd.browseBatches': '🗂️ Browse Implementation Batches',
  'sdd.browseBacklog': '🗒️ Browse Backlog',
  'sdd.browseDecisions': '⚖️ Browse Architecture Decisions',
  'sdd.browseHandoffs': '🔄 Browse Agent Handoffs',
  'sdd.autoGardening': '🌱 Memory monitoring: {status}',
  'sdd.runGardening': '🧹 Run Memory Gardening',
  'sdd.createGardening': '➕ Create Gardening Request',
  'tooltip.sdd.selectScope': 'Select the repository whose SDD records you want to inspect. Use it whenever the workspace contains more than one governed project.',
  'tooltip.sdd.viewMode': 'Switch Markdown documents between preview, source, and side-by-side views. It only changes the editor presentation.',
  'tooltip.sdd.openCurrent': 'Open the active request pointer for the selected SDD scope. Use it to confirm the approved work before implementation.',
  'tooltip.sdd.openSpec': 'Open the normative specification for the selected scope. Consult it before changing contracts or acceptance criteria.',
  'tooltip.sdd.openChecklist': 'Open the validation checklist where executable evidence is recorded. Use it while verifying the current batch.',
  'tooltip.sdd.browseRequests': 'Browse formal human requests for the selected scope. Backlog ideas remain non-executable until promoted here.',
  'tooltip.sdd.browseBatches': 'Browse operational batch records and their implementation status. Use it to resume the active batch without duplicating work.',
  'tooltip.sdd.browseBacklog': 'Browse incubated SDD ideas and their status. This view never starts implementation directly from a backlog item.',
  'tooltip.sdd.browseDecisions': 'Browse approved architecture decisions for the current scope. Use them to keep local implementation aligned with governance.',
  'tooltip.sdd.browseHandoffs': 'Browse agent handoffs that record the current execution context. Use them to coordinate review without changing Git history.',
  'tooltip.sdd.autoGardening': 'Monitor the 50 KB / 200-line warning and 75 KB / 300-line pruning ceiling. Healthy memory is never rewritten automatically.',
  'tooltip.sdd.runGardening': 'Validate the selected execution memory against the 50 KB warning and 75 KB ceiling. Pruning healthy files below the warning is prohibited.',
  'tooltip.sdd.createGardening': 'Prepare a formal gardening request instead of editing governed records ad hoc. Review and approve that request before implementation.',
  'sdd.scopePrompt': 'Select the SDD repository scope:',
  'sdd.scopeChanged': 'SDD scope: {scope}',
  'sdd.folderMissing': 'The SDD folder was not found for {scope}.',
  'sdd.fileMissing': 'Document not found: {path} ({scope})',
  'core.updateAll': '🔄 Update Core System',
  'core.syncResources': '📦 Sync Resources',
  'core.cssRebuild': '⚡ Rebuild CSS for {target}',
  'core.cssAudit': '🔍 Audit CSS for {target}',
  'tooltip.core.updateAll': 'Run the official local Core update pipeline. Use it to synchronize the system in the test environment through its guarded steps.',
  'tooltip.core.syncResources': 'Compile and synchronize authored resources through the official pipeline. Use it after changing resource inputs, never as a manual file copy.',
  'tooltip.core.cssRebuild': 'Rebuild derived CSS for the selected project. Use it after changing Tailwind-dependent templates or resources.',
  'tooltip.core.cssAudit': 'Inspect CSS provenance and coverage for the selected project. Use it to diagnose stale or unrecognized generated styles.',
  'release.verify': '🔐 Verify Release Permission',
  'release.productManager': 'Gestor',
  'release.productInstaller': 'Gestor Installer',
  'release.manager': '🚀 Prepare Gestor Release',
  'release.installer': '🚀 Prepare Gestor Installer Release',
  'release.permissionAllowed': 'Release permission: {permission}',
  'release.permissionDenied': 'Release actions are unavailable with GitHub permission {permission}.',
  'release.permissionUnknown': 'Release permission could not be verified: {reason}',
  'release.preflightFailed': 'Release preflight failed: {reason}',
  'release.selectType': 'Select the release increment:',
  'release.selectMode': 'Select the official release mode:',
  'release.tagMessage': 'Annotated tag summary',
  'release.commitMessage': 'Release commit message',
  'release.confirm': 'Run {product} release {current} → {next} ({tag}) using {mode}?',
  'release.started': '{product} release started in a dedicated task.',
  'release.completed': '{product} release completed successfully.',
  'release.openActions': '🐙 Open GitHub Actions',
  'tooltip.release.verify': 'Check GitHub authentication and release permission before preparing a release. It does not modify the repository or publish anything.',
  'tooltip.release.manager': 'Start phase 1 of the Gestor release flow and save an editable preparation draft. No commit, tag, or remote action occurs in this phase.',
  'tooltip.release.installer': 'Start phase 1 of the Gestor Installer release flow and save an editable preparation draft. It remains local until phase 2 passes every gate.',
  'tooltip.release.executeManager': 'Run phase 2 for a prepared Gestor release only after all local and permission checks pass. This can create remote Git and GitHub effects.',
  'tooltip.release.executeInstaller': 'Run phase 2 for a prepared Gestor Installer release only after all local and permission checks pass. This can create remote Git and GitHub effects.',
  'tooltip.release.openActions': 'Open GitHub Actions to inspect the workflow associated with a permitted release. It does not trigger a new workflow.',
  'release.formTitle': 'Create {product} Release',
  'release.formDescription': 'Review the computed version and provide the release messages in this single form.',
  'release.impact': 'Remote operation: creates a commit and tag and may publish through GitHub Actions.',
  'release.currentVersion': 'Current version',
  'release.nextVersion': 'Next version',
  'release.tag': 'Release tag',
  'release.command': 'Official command',
  'release.type': 'Version increment',
  'release.mode': 'Release mode',
  'release.modeAutomatic': 'Automatic — push tag and let GitHub Actions publish',
  'release.modeManual': 'Manual — publish with GitHub CLI',
  'release.workflow': 'Affected workflow: {workflow}',
  'release.permissionChecking': 'Checking GitHub authentication and release permission…',
  'release.cleanRequired': 'The Core working tree must be clean before a release.',
  'release.tagExists': 'The tag {tag} already exists.',
  'projects.setTarget': '🎯 Select Target Project',
  'projects.updateAll': '🔄 Update Target Project [{target}]',
  'projects.deploy': '🚀 Deploy Target Project [{target}]',
  'projects.syncCore': '➡️ Sync Core → Project [{target}]',
  'projects.syncFiles': '☁️ Sync Files → Test Environment [{target}]',
  'projects.updateSelect': '📋 Update Another Project…',
  'projects.deploySelect': '📤 Deploy Another Project…',
  'projects.scaffold': '🆕 Create Satellite Project',
  'projects.register': '➕ Register Existing Project',
  'projects.clone': '📥 Clone Missing Repositories',
  'projects.syncTemplate': '🔃 Sync Environment Template',
  'tooltip.projects.setTarget': 'Select the project used by contextual project commands. Choosing a target only changes workspace state.',
  'tooltip.projects.updateAll': 'Run the full official update pipeline for the selected project in its test environment. Use it after coordinated Core or project changes.',
  'tooltip.projects.syncCore': 'Synchronize the Core layer into the selected project through the approved project pipeline. Use it before validating project integration.',
  'tooltip.projects.syncFiles': 'Synchronize selected project files to its local test environment with the official task. Do not use manual mirror copies.',
  'tooltip.projects.deploy': 'Deploy the selected project using its configured deployment workflow. Review the target and confirmation form before continuing.',
  'tooltip.projects.updateSelect': 'Choose another project and run its complete update pipeline. Use it when the current target should remain unchanged.',
  'tooltip.projects.deploySelect': 'Choose a project for deployment without changing the default target. Confirm the remote impact in the presented form.',
  'tooltip.projects.scaffold': 'Create the standard structure for a new satellite project. Use it only when beginning a separately managed project.',
  'tooltip.projects.register': 'Register an existing project in the environment configuration. This makes it available for explicit project commands.',
  'tooltip.projects.clone': 'Clone configured repositories that are missing beside the workspace. Use it to repair a partial local checkout.',
  'tooltip.projects.syncTemplate': 'Synchronize the active environment configuration with its Core template. Review the resulting configuration before project operations.',
  'projects.noTargetWarning': 'Select a valid target project before running this action.',
  'projects.selectPrompt': 'Select a project:',
  'projects.targetPrompt': 'Select the default target project:',
  'projects.targetChanged': 'Target project: {target}',
  'projects.environmentMissing': 'The active environment.json was not found.',
  'projects.templateMissing': 'The environment.json template was not found.',
  'projects.idPrompt': 'Unique project identifier (lowercase slug):',
  'projects.namePrompt': 'Project display name:',
  'projects.urlPrompt': 'Project base URL:',
  'projects.localPrompt': 'Does the project run in the local Docker environment?',
  'projects.saved': 'Project {name} ({id}) was registered in environment.json.',
  'projects.scaffolded': 'Satellite project {name} ({id}) was created.',
  'projects.syncSucceeded': 'The active environment was synchronized with the template.',
  'projects.githubOwnerPrompt': 'GitHub organization or owner for the Conn2Flow repositories:',
  'projects.clonePrompt': 'Select an official repository to clone:',
  'projects.allPresent': 'All configured repositories are present beside the workspace.',
  'projects.missingRepositories': 'Missing repositories: {names}.',
  'diagnostics.dockerStatus': '🐳 Docker Container Status',
  'diagnostics.apacheLogs': '📜 Follow Apache Logs',
  'diagnostics.phpLogs': '🐘 Follow PHP Logs',
  'diagnostics.truncatePhp': '🗑️ Clear PHP Error Log',
  'diagnostics.aiSync': '🔌 Validate and Sync Skills',
  'diagnostics.syncAll': '📡 Distribute Skills to Repositories',
  'tooltip.diagnostics.dockerStatus': 'Show the health and state of local Docker containers. Use it before diagnosing services that depend on the development stack.',
  'tooltip.diagnostics.apacheLogs': 'Start or stop following Apache logs in a dedicated terminal. Use it while reproducing HTTP or routing issues locally.',
  'tooltip.diagnostics.phpLogs': 'Start or stop following PHP logs in a dedicated terminal. Use it while reproducing server-side errors locally.',
  'tooltip.diagnostics.truncatePhp': 'Clear the local PHP error log after reviewing it. Use it to isolate a fresh reproduction, as previous log evidence is removed.',
  'tooltip.diagnostics.aiSync': 'Validate the AI-kit contracts and synchronization state. Use it after changing shared instructions, skills, or agent definitions.',
  'tooltip.diagnostics.syncAll': 'Run the configured distribution workflow for shared skills across repositories. Review its target repositories before starting the task.',
  'agents.selectMode': '⚙️ Select Agent Topology or Autonomy',
  'modes.selectTopology': 'Select the agent topology:',
  'modes.selectAutonomy': 'Select the autonomy level:',
  'agents.launchClaude': '▶️ Start Claude Code (/goal)',
  'agents.copyPrompt': '📋 Copy Executor Prompt',
  'agents.recordHandoff': '🔗 Open Current Handoff',
  'agents.prepareReview': '🔍 Prepare Architect Review',
  'agents.reviewReady': 'Handoff opened and Source Control focused. Review and publish manually when ready.',
  'agents.activeMissing': 'The active request was not found in sdd/human-requests/CURRENT.md.',
  'agents.promptCopied': 'Executor prompt copied to the clipboard.',
  'agents.handoffOpened': 'The current handoff was opened for editing.',
  'agents.launchPrompt': 'How should Claude Code be started?',
  'agents.copyOption': 'Copy prompt for the Claude extension',
  'agents.cliOption': 'Run Claude CLI in a task',
  'agents.npxOption': 'Run with NPX',
  'agents.installOption': 'Install Claude CLI globally',
  'agents.started': 'Claude Code started for {request}.',
  'agents.goalInstruction': '/goal [Project: {repo} | Root: {root} | Entry: {currentPath} | Topology: {topology} | Autonomy: {autonomy}] Read the active brief in sdd/human-requests/CURRENT.md ({request}), complete its Live Todo List under SDD governance, validate locally, update the validation checklist and current handoff. Do not commit, push, deploy or release without explicit human authorization.',
  'agents.executorPrompt': '---\n🏷️ TARGET PROJECT IDENTIFICATION:\n- Project: {repo}\n- Root Path: {root}\n- SDD Root: {sddRoot}\n- Entry File: {currentPath}\n- Agent Topology: {topology}\n- Autonomy Level: {autonomy}\n---\n\n{roles}\n\nYou are the Conn2Flow SDD Executor. Implement the approved active request [{request}]({currentPath}), maintain its Live Todo List, validate locally and record evidence in the validation checklist and current handoff. Never use broad Git staging, never copy files manually into test mirrors, and never commit, push, deploy or release without explicit human authorization.\n\nACTIVE REQUEST ({request})\n\n{content}',
  'agents.roles.dual': 'Dual-agent topology: the human Chief Engineer and you as Executor. There is no separate reviewer agent, so run the findings-first self-review yourself before handing the batch back.',
  'agents.roles.triad': 'Triad topology: Architect (specs and decisions), you as Executor (code and evidence) and a separate Reviewer agent. Stop at the validation evidence and leave the audit to the reviewer.',
  'agents.handoffInitial': '# 🤝 Executor Agent Handoff — {request}\n\n---\n🏷️ TARGET PROJECT IDENTIFICATION:\n- Project: {repo}\n- Root Path: {root}\n- SDD Root: {sddRoot}\n- Entry File: {currentPath}\n---\n\n* **Date**: {timestamp}\n* **Status**: In Progress\n\n## 🖥️ Terminal Log and Technical Decisions\n<!-- Paste the terminal execution log here -->\n',
  'docs.index': '📚 Documentation Index',
  'docs.panel': '📊 Dev Tools Panel Manual',
  'docs.marketplace': '🛒 VS Code Marketplace Publication Guide',
  'docs.cli': '💻 CLI and MCP Quick Guide',
  'docs.orchestration': '🧭 Multi-Agent Orchestration Playbook',
  'docs.architecture': '🏛️ Dual-Agent Architecture',
  'docs.skills': '🧠 Skills Catalog',
  'docs.roadmap': '🛣️ Future Evolution Roadmap',
  'tooltip.docs.index': 'Open the bilingual documentation index. Use it to browse every maintained guide from the authoritative workspace catalog.',
  'tooltip.docs.panel': 'Open the Dev Tools Panel Manual v2. Use it to understand the tree, controls, release phases, watcher, and integrated SDD actions.',
  'tooltip.docs.cli': 'Open the CLI and MCP quick guide. Use it to find official commands, MCP Hub setup, and supported local workflows.',
  'tooltip.docs.orchestration': 'Open the multi-agent orchestration playbook. Use it to coordinate architect, executor, reviewer, and MCP handoffs.',
  'tooltip.docs.architecture': 'Open the dual-agent and triad architecture guide. Use it to choose responsibilities and autonomy for a governed task.',
  'tooltip.docs.skills': 'Open the catalog of available framework and SDD skills. Use it to identify the required operational guidance before a task.',
  'tooltip.docs.roadmap': 'Open the future evolution roadmap. Use it to understand planned capabilities without treating backlog ideas as implemented contracts.',
  'settings.language': '🌐 Select Extension Language',
  'settings.terminal': 'Terminal Mode: {mode}',
  'language.auto': 'Automatic (VS Code)',
  'language.pt-BR': 'Português (Brasil)',
  'language.en': 'English',
  'language.changed': 'Extension language changed to {language}.',
  'language.reload': 'Reload Window may be required to translate Command Palette entries.',
  'terminal.reuse': 'Reuse dedicated terminal',
  'terminal.new': 'Create a new terminal per command',
  'command.confirm': 'Run “{label}” for {target}?',
  'command.confirmButton': 'Run',
  'command.formTitle': 'Confirm {label}',
  'command.impact': 'Impact classification: {impact}',
  'command.target': 'Target',
  'command.command': 'Command',
  'command.acknowledge': 'I reviewed the target and command',
  'command.trustRequired': 'Trust this workspace before running Conn2Flow commands.',
  'command.started': '{label} started.',
  'command.succeeded': '{label} completed successfully.',
  'command.progressTitle': 'Running {label}',
  'command.progressRunning': 'The dedicated task is running; progress remains visible until it exits.',
  'command.failed': '{label} failed with exit code {code}.',
  'command.busy': 'Another exclusive Conn2Flow pipeline is already running.',
  'custom.edit': 'Edit Project Actions',
  'tooltip.custom.edit': 'Open the project action manifest for deliberate editing. Use it to define local actions before they appear in this section.',
  'custom.trustRequired': 'Custom project actions are disabled in an untrusted workspace.',
  'custom.created': 'The .c2f/actions.json manifest was created and opened for editing.',
  'backlog.all': 'All statuses',
  'backlog.filterPrompt': 'Filter backlog items by status:',
  'backlog.itemPrompt': '[{scope}] Select a backlog item:',
  'backlog.empty': 'No backlog items were found for {scope}.',
  'backlog.drift': 'Status drift: index={index}, file={file}',
  'backlog.openIndex': 'Open BACKLOG-INDEX.md',
  'backlog.promote': 'Promote Backlog Item to Request',
  'backlog.intakeGate': 'Promotion requires an explicit governed SDD request. No implementation will start automatically.',
  'backlog.promotionDraft': 'Create a governed request draft for {id}?',
  'backlog.promotionPrompt': 'Prepare a governed SDD request for backlog item {id}.\nType: {type}\nStatus: {status}\nTitle: {title}\nNext action: {action}\nSource: sdd/backlog/{file}\n\nUse start-sdd-slice. Do not implement until the new request is explicitly approved.',
  'sdd.noFiles': 'No Markdown files were found in {directory} for {scope}.',
  'sdd.selectFile': '[{scope}] Select a file from {title}:',
  'sdd.currentFile': 'Active request',
  'logs.apacheStarted': 'Following Apache logs.',
  'logs.apacheStopped': 'Apache log follow stopped.',
  'logs.phpStarted': 'Following PHP logs.',
  'logs.phpStopped': 'PHP log follow stopped.',
  'mode.supervised': '🛡️ Supervised',
  'mode.monitored': '👁️ Autonomous Monitored',
  'mode.headless': '🤖 Autonomous Headless',
  'mode.triad': '🏛️ Agent Triad',
  'mode.dual': '👥 Dual Agent',
  'view.preview': 'Rendered Preview',
  'view.code': 'Source Code',
  'view.both': 'Side by Side',
  'gardening.enabled': 'enabled',
  'gardening.disabled': 'disabled',
  'gardening.healthyLabel': '🟢 Healthy: {sizeKb} KB ({lineCount} lines)',
  'gardening.warningLabel': '🟡 Attention: {sizeKb} KB / {lineCount} lines (Warning: 50 KB / 200 lines)',
  'gardening.criticalLabel': '🔴 Critical: {sizeKb} KB / {lineCount} lines (Ceiling: 75 KB / 300 lines)',
  'gardening.readError': 'Unable to read execution memory',
  'gardening.noPruneHealthy': 'Memory is healthy at {sizeKb} KB / {lineCount} lines. Pruning below 50 KB / 200 lines is prohibited.',
  'status.sddTooltip': 'Open the active SDD request',
  'status.modesTooltip': 'Change agent topology or autonomy',
  'status.dockerTooltip': 'Inspect active Docker containers',
  'release.executeManager': 'Execute Gestor Release',
  'release.executeInstaller': 'Execute Gestor Installer Release',
  'release.notPrepared': 'Run Prepare Release before execution.',
  'release.coreMissing': 'The Conn2Flow Core repository was not found.',
  'release.cleanTree': 'Clean working tree',
  'release.docsReady': '{count} release documentation files checked and synchronized',
  'release.docsBlocked': 'Documentation requires attention: {issues}',
  'release.prepareTitle': 'Prepare {product} Release',
  'release.prepareDescription': 'Phase 1 collects diagnostics and saves an editable draft without changing the repository.',
  'release.prepareImpact': 'Execution remains locked until permission, Git, tag, workflow and documentation gates pass.',
  'release.saveDraft': 'Save Preparation',
  'release.branch': 'Current branch',
  'release.permission': 'GitHub permission',
  'release.modifiedFiles': 'Modified files',
  'release.documentation': 'Pre-release documentation',
  'release.releaseNotes': 'Release notes draft',
  'release.draftSaved': 'Release draft saved in workspace state.',
  'release.executeReady': 'Phase 2 is ready.',
  'release.executionBlocked': 'Phase 2 is locked: {blockers}',
  'release.openPreparation': 'Open Preparation',
  'release.openScm': 'Source Control',
  'release.blocker.workspace-untrusted': 'the workspace is not trusted',
  'release.blocker.permission-denied': 'GitHub release permission was denied',
  'release.blocker.permission-unknown': 'GitHub release permission could not be verified',
  'release.blocker.dirty-tree': 'the working tree has uncommitted changes',
  'release.blocker.detached-head': 'Git is in detached HEAD state',
  'release.blocker.non-github-remote': 'origin is not a GitHub repository',
  'release.blocker.tag-collision': 'the calculated tag already exists',
  'release.blocker.documentation-outdated': 'release documentation is missing or outdated',
  'release.blocker.draft-missing': 'the release preparation draft is missing',
  'release.blocker.required-file-missing': 'a required release file is missing',
  'release.blocker.workflow-busy': 'the release workflow is already running',
  'release.workflowMissing': 'The GitHub Actions run was not found.',
  'agents.hubWatcherActive': '🟢 Triad Watcher: ACTIVE (Listening to MCP Hub)',
  'agents.hubWatcherPaused': '⚪ Triad Watcher: PAUSED',
  'tooltip.agents.hubWatcherActive': 'Pause the MCP Hub task watcher when automatic task notifications should be temporarily quiet. Re-enable it to receive task updates again.',
  'tooltip.agents.hubWatcherPaused': 'Enable the MCP Hub task watcher to receive dispatched-task and executor-receipt updates. It observes the Hub without executing a task.',
  'hub.taskDispatched': 'Conn2Flow: Running {req}…',
  'hub.executorCompleted': 'Conn2Flow: Executor receipt emitted for {batch}. Ready for review!',
  'hub.watcherStarted': 'Triad Watcher is now active.',
  'hub.watcherPaused': 'Triad Watcher is paused.',
  'release.saveAndExecute': 'Save and Execute Release',
  'release.executing': 'Executing release…',
  'release.progress': 'Releasing {product}',
  'release.workflowProgress': 'Waiting for {product} workflow',
  'release.preparingFeedback': 'Preparing {product} Release…',
  'common.loading': 'Loading…',
  'tooltip.agents.launchClaude': 'Start the approved executor workflow with the generated SDD context. Use it after confirming the active request and its autonomy mode.',
  'tooltip.agents.copyPrompt': 'Copy a complete executor prompt containing the target repository and active request. Use it to hand work to a supported agent manually.',
  'tooltip.agents.recordHandoff': 'Open the current executor handoff for the selected scope. Record decisions and validation evidence there for the next reviewer.',
  'tooltip.agents.prepareReview': 'Open the current handoff and focus Source Control for architect review. It does not commit, push, or publish changes.',
  'tooltip.custom.action': 'Run this action from the trusted project manifest. Review its configured command or file target before continuing.'
} as const;

export type TranslationKey = keyof typeof en;

export const ptBR: Record<TranslationKey, string> = {
  'common.active': 'Ativo',
  'common.none': 'Nenhum',
  'common.unknown': 'Desconhecido',
  'common.cancelled': 'Operação cancelada.',
  'common.cancel': 'Cancelar',
  'common.submit': 'Continuar',
  'common.invalidForm': 'Revise os campos obrigatórios e os valores permitidos.',
  'common.noWorkspace': 'Abra um workspace no VS Code para usar esta ação.',
  'common.error': 'Falha na operação: {message}',
  'common.yesLocal': 'Sim (Ambiente de Testes Local)',
  'common.noRemote': 'Não (Produção Remota)',
  'section.overview': '🎛️ Controles Principais',
  'section.sdd': '📐 SDD & Planejamento',
  'section.core': '⚡ Core & Releases',
  'section.projects': '📁 Projetos & Ambiente de Testes',
  'section.diagnostics': '🩺 Ambiente & Diagnóstico',
  'section.agents': '📚 Documentação & Configurações',
  'section.custom': '🧩 Ações do Projeto',
  'overview.scope': '🎯 Escopo SDD: {scope}',
  'overview.target': '📌 Projeto Alvo: {target}',
  'overview.noTarget': '📌 Projeto Alvo: não selecionado',
  'overview.language': '🌐 Idioma da Extensão: {language}',
  'overview.topology': '👥 Topologia: {mode}',
  'overview.autonomy': '🛡️ Autonomia: {mode}',
  'sdd.selectScope': '🎯 Selecionar Escopo SDD',
  'sdd.viewMode': '👁️ Exibição Markdown: {mode}',
  'sdd.openCurrent': '📋 Abrir CURRENT.md',
  'sdd.openSpec': '📜 Abrir SPEC.md',
  'sdd.openChecklist': '✅ Abrir Checklist de Validação',
  'sdd.browseRequests': '📥 Navegar Requisições Humanas',
  'sdd.browseBatches': '🗂️ Navegar Lotes de Implementação',
  'sdd.browseBacklog': '🗒️ Navegar Backlog',
  'sdd.browseDecisions': '⚖️ Navegar Decisões Arquiteturais',
  'sdd.browseHandoffs': '🔄 Navegar Handoffs de Agentes',
  'sdd.autoGardening': '🌱 Monitoramento de memória: {status}',
  'sdd.runGardening': '🧹 Executar Memory Gardening',
  'sdd.createGardening': '➕ Criar Requisição de Gardening',
  'sdd.scopePrompt': 'Selecione o repositório do escopo SDD:',
  'sdd.scopeChanged': 'Escopo SDD: {scope}',
  'sdd.folderMissing': 'A pasta SDD não foi encontrada para {scope}.',
  'sdd.fileMissing': 'Documento não encontrado: {path} ({scope})',
  'core.updateAll': '🔄 Atualizar Sistema Core',
  'core.syncResources': '📦 Sincronizar Recursos',
  'core.cssRebuild': '⚡ Reconstruir CSS de {target}',
  'core.cssAudit': '🔍 Auditar CSS de {target}',
  'release.verify': '🔐 Verificar Permissão de Release',
  'release.productManager': 'Gestor',
  'release.productInstaller': 'Gestor Instalador',
  'release.manager': '🚀 Preparar Release do Gestor',
  'release.installer': '🚀 Preparar Release do Gestor Instalador',
  'release.permissionAllowed': 'Permissão de release: {permission}',
  'release.permissionDenied': 'As ações de release não estão disponíveis com a permissão GitHub {permission}.',
  'release.permissionUnknown': 'Não foi possível verificar a permissão de release: {reason}',
  'release.preflightFailed': 'O preflight de release falhou: {reason}',
  'release.selectType': 'Selecione o incremento do release:',
  'release.selectMode': 'Selecione o modo oficial de release:',
  'release.tagMessage': 'Resumo da tag anotada',
  'release.commitMessage': 'Mensagem do commit de release',
  'release.confirm': 'Executar release de {product} {current} → {next} ({tag}) no modo {mode}?',
  'release.started': 'Release de {product} iniciado em uma tarefa dedicada.',
  'release.completed': 'Release de {product} concluído com sucesso.',
  'release.openActions': '🐙 Abrir GitHub Actions',
  'release.formTitle': 'Criar Release do {product}',
  'release.formDescription': 'Revise a versão calculada e informe as mensagens do release neste único formulário.',
  'release.impact': 'Operação remota: cria commit e tag e pode publicar pelo GitHub Actions.',
  'release.currentVersion': 'Versão atual',
  'release.nextVersion': 'Próxima versão',
  'release.tag': 'Tag do release',
  'release.command': 'Comando oficial',
  'release.type': 'Incremento de versão',
  'release.mode': 'Modo de release',
  'release.modeAutomatic': 'Automático — envia a tag e deixa o GitHub Actions publicar',
  'release.modeManual': 'Manual — publica usando GitHub CLI',
  'release.workflow': 'Workflow afetado: {workflow}',
  'release.permissionChecking': 'Verificando autenticação GitHub e permissão de release…',
  'release.cleanRequired': 'A árvore de trabalho do Core deve estar limpa antes de um release.',
  'release.tagExists': 'A tag {tag} já existe.',
  'projects.setTarget': '🎯 Selecionar Projeto Alvo',
  'projects.updateAll': '🔄 Atualizar Projeto Alvo [{target}]',
  'projects.deploy': '🚀 Deploy do Projeto Alvo [{target}]',
  'projects.syncCore': '➡️ Sincronizar Core → Projeto [{target}]',
  'projects.syncFiles': '☁️ Sincronizar Arquivos → Ambiente de Testes [{target}]',
  'projects.updateSelect': '📋 Atualizar Outro Projeto…',
  'projects.deploySelect': '📤 Deploy de Outro Projeto…',
  'projects.scaffold': '🆕 Criar Projeto Satélite',
  'projects.register': '➕ Cadastrar Projeto Existente',
  'projects.clone': '📥 Clonar Repositórios Ausentes',
  'projects.syncTemplate': '🔃 Sincronizar Template do Environment',
  'projects.noTargetWarning': 'Selecione um projeto alvo válido antes de executar esta ação.',
  'projects.selectPrompt': 'Selecione um projeto:',
  'projects.targetPrompt': 'Selecione o projeto alvo padrão:',
  'projects.targetChanged': 'Projeto alvo: {target}',
  'projects.environmentMissing': 'O environment.json ativo não foi encontrado.',
  'projects.templateMissing': 'O template de environment.json não foi encontrado.',
  'projects.idPrompt': 'Identificador único do projeto (slug em minúsculas):',
  'projects.namePrompt': 'Nome de exibição do projeto:',
  'projects.urlPrompt': 'URL base do projeto:',
  'projects.localPrompt': 'O projeto roda no ambiente local Docker?',
  'projects.saved': 'Projeto {name} ({id}) cadastrado no environment.json.',
  'projects.scaffolded': 'Projeto satélite {name} ({id}) criado.',
  'projects.syncSucceeded': 'O environment ativo foi sincronizado com o template.',
  'projects.githubOwnerPrompt': 'Organização ou owner GitHub dos repositórios Conn2Flow:',
  'projects.clonePrompt': 'Selecione um repositório oficial para clonar:',
  'projects.allPresent': 'Todos os repositórios configurados estão presentes ao lado do workspace.',
  'projects.missingRepositories': 'Repositórios ausentes: {names}.',
  'diagnostics.dockerStatus': '🐳 Status dos Containers Docker',
  'diagnostics.apacheLogs': '📜 Acompanhar Logs Apache',
  'diagnostics.phpLogs': '🐘 Acompanhar Logs PHP',
  'diagnostics.truncatePhp': '🗑️ Limpar Log de Erros PHP',
  'diagnostics.aiSync': '🔌 Validar e Sincronizar Skills',
  'diagnostics.syncAll': '📡 Distribuir Skills para Repositórios',
  'agents.selectMode': '⚙️ Selecionar Topologia ou Autonomia',
  'modes.selectTopology': 'Selecione a topologia de agentes:',
  'modes.selectAutonomy': 'Selecione o nível de autonomia:',
  'agents.launchClaude': '▶️ Iniciar Claude Code (/goal)',
  'agents.copyPrompt': '📋 Copiar Prompt do Executor',
  'agents.recordHandoff': '🔗 Abrir Handoff Atual',
  'agents.prepareReview': '🔍 Preparar Revisão do Arquiteto',
  'agents.reviewReady': 'Handoff aberto e Controle de Código-Fonte em foco. Revise e publique manualmente quando estiver pronto.',
  'agents.activeMissing': 'A requisição ativa não foi encontrada em sdd/human-requests/CURRENT.md.',
  'agents.promptCopied': 'Prompt do executor copiado para a área de transferência.',
  'agents.handoffOpened': 'O handoff atual foi aberto para edição.',
  'agents.launchPrompt': 'Como o Claude Code deve ser iniciado?',
  'agents.copyOption': 'Copiar prompt para a extensão do Claude',
  'agents.cliOption': 'Executar Claude CLI em uma tarefa',
  'agents.npxOption': 'Executar via NPX',
  'agents.installOption': 'Instalar Claude CLI globalmente',
  'agents.started': 'Claude Code iniciado para {request}.',
  'agents.goalInstruction': '/goal [Projeto: {repo} | Raiz: {root} | Entrada: {currentPath} | Topologia: {topology} | Autonomia: {autonomy}] Leia o briefing ativo em sdd/human-requests/CURRENT.md ({request}), conclua a Live Todo List sob governança SDD, valide localmente e atualize o checklist de validação e o handoff atual. Não execute commit, push, deploy ou release sem autorização humana explícita.',
  'agents.executorPrompt': '---\n🏷️ IDENTIFICAÇÃO DO PROJETO ALVO:\n- Projeto: {repo}\n- Caminho Raiz: {root}\n- Raiz SDD: {sddRoot}\n- Arquivo de Entrada: {currentPath}\n- Topologia de Agentes: {topology}\n- Nível de Autonomia: {autonomy}\n---\n\n{roles}\n\nVocê é o Executor SDD do Conn2Flow. Implemente a requisição ativa aprovada [{request}]({currentPath}), mantenha a Live Todo List, valide localmente e registre evidências no checklist de validação e no handoff atual. Nunca use staging Git amplo, nunca copie arquivos manualmente para espelhos de teste e nunca execute commit, push, deploy ou release sem autorização humana explícita.\n\nREQUISIÇÃO ATIVA ({request})\n\n{content}',
  'agents.roles.dual': 'Topologia de agente duplo: o Engenheiro Chefe humano e você como Executor. Não há agente revisor separado, então faça você mesmo o autorreview findings-first antes de devolver o lote.',
  'agents.roles.triad': 'Topologia de tríade: Arquiteto (specs e decisões), você como Executor (código e evidências) e um agente Revisor separado. Pare nas evidências de validação e deixe a auditoria para o revisor.',
  'agents.handoffInitial': '# 🤝 Handoff do Agente Executor — {request}\n\n---\n🏷️ IDENTIFICAÇÃO DO PROJETO ALVO:\n- Projeto: {repo}\n- Caminho Raiz: {root}\n- Raiz SDD: {sddRoot}\n- Arquivo de Entrada: {currentPath}\n---\n\n* **Data**: {timestamp}\n* **Status**: Em Andamento\n\n## 🖥️ Log do Terminal e Decisões Técnicas\n<!-- Cole aqui o log da execução do terminal -->\n',
  'docs.index': '📚 Índice de Documentações',
  'docs.panel': '📊 Manual do Painel Dev Tools',
  'docs.marketplace': '🛒 Guia de Publicação no Marketplace VS Code',
  'docs.cli': '💻 Guia Rápido de CLI e MCP',
  'docs.orchestration': '🧭 Playbook de Orquestração Multi-Agentes',
  'docs.architecture': '🏛️ Arquitetura de Agente Duplo',
  'docs.skills': '🧠 Catálogo de Skills',
  'docs.roadmap': '🛣️ Roteiro de Evolução Futura',
  'settings.language': '🌐 Selecionar Idioma da Extensão',
  'settings.terminal': 'Modo de Terminal: {mode}',
  'language.auto': 'Automático (VS Code)',
  'language.pt-BR': 'Português (Brasil)',
  'language.en': 'English',
  'language.changed': 'Idioma da extensão alterado para {language}.',
  'language.reload': 'Pode ser necessário recarregar a janela para traduzir entradas da Paleta de Comandos.',
  'terminal.reuse': 'Reutilizar terminal dedicado',
  'terminal.new': 'Criar novo terminal por comando',
  'command.confirm': 'Executar “{label}” para {target}?',
  'command.confirmButton': 'Executar',
  'command.formTitle': 'Confirmar {label}',
  'command.impact': 'Classificação de impacto: {impact}',
  'command.target': 'Alvo',
  'command.command': 'Comando',
  'command.acknowledge': 'Revisei o alvo e o comando',
  'command.trustRequired': 'Confie neste workspace antes de executar comandos Conn2Flow.',
  'command.started': '{label} iniciado.',
  'command.succeeded': '{label} concluído com sucesso.',
  'command.progressTitle': 'Executando {label}',
  'command.progressRunning': 'A tarefa dedicada está em execução; o progresso permanecerá visível até ela terminar.',
  'command.failed': '{label} falhou com código de saída {code}.',
  'command.busy': 'Outro pipeline exclusivo do Conn2Flow já está em execução.',
  'custom.edit': 'Editar Ações do Projeto',
  'custom.trustRequired': 'Ações personalizadas estão desativadas em workspace não confiável.',
  'custom.created': 'O manifesto .c2f/actions.json foi criado e aberto para edição.',
  'backlog.all': 'Todos os status',
  'backlog.filterPrompt': 'Filtre os itens de backlog por status:',
  'backlog.itemPrompt': '[{scope}] Selecione um item do backlog:',
  'backlog.empty': 'Nenhum item de backlog foi encontrado para {scope}.',
  'backlog.drift': 'Divergência de status: índice={index}, arquivo={file}',
  'backlog.openIndex': 'Abrir BACKLOG-INDEX.md',
  'backlog.promote': 'Promover Item do Backlog para Requisição',
  'backlog.intakeGate': 'A promoção exige uma requisição SDD governada e explícita. Nenhuma implementação será iniciada automaticamente.',
  'backlog.promotionDraft': 'Criar um rascunho governado de requisição para {id}?',
  'backlog.promotionPrompt': 'Prepare uma requisição SDD governada para o item de backlog {id}.\nTipo: {type}\nStatus: {status}\nTítulo: {title}\nPróxima ação: {action}\nFonte: sdd/backlog/{file}\n\nUse start-sdd-slice. Não implemente até a nova requisição ser aprovada explicitamente.',
  'sdd.noFiles': 'Nenhum arquivo Markdown foi encontrado em {directory} para {scope}.',
  'sdd.selectFile': '[{scope}] Selecione um arquivo de {title}:',
  'sdd.currentFile': 'Requisição ativa',
  'logs.apacheStarted': 'Acompanhando logs Apache.',
  'logs.apacheStopped': 'Acompanhamento de logs Apache encerrado.',
  'logs.phpStarted': 'Acompanhando logs PHP.',
  'logs.phpStopped': 'Acompanhamento de logs PHP encerrado.',
  'mode.supervised': '🛡️ Supervisionado',
  'mode.monitored': '👁️ Autônomo Monitorado',
  'mode.headless': '🤖 Autônomo Headless',
  'mode.triad': '🏛️ Tríade de Agentes',
  'mode.dual': '👥 Duplo Agente',
  'view.preview': 'Preview Renderizado',
  'view.code': 'Código-Fonte',
  'view.both': 'Lado a Lado',
  'gardening.enabled': 'ativado',
  'gardening.disabled': 'desativado',
  'gardening.healthyLabel': '🟢 Saudável: {sizeKb} KB ({lineCount} linhas)',
  'gardening.warningLabel': '🟡 Atenção: {sizeKb} KB / {lineCount} linhas (Alerta: 50 KB / 200 linhas)',
  'gardening.criticalLabel': '🔴 Crítico: {sizeKb} KB / {lineCount} linhas (Teto: 75 KB / 300 linhas)',
  'gardening.readError': 'Erro ao ler a memória de execução',
  'gardening.noPruneHealthy': 'A memória está saudável em {sizeKb} KB / {lineCount} linhas. É proibido podar abaixo de 50 KB / 200 linhas.',
  'status.sddTooltip': 'Abrir a requisição SDD ativa',
  'status.modesTooltip': 'Alterar topologia de agentes ou autonomia',
  'status.dockerTooltip': 'Inspecionar containers Docker ativos',
  'release.executeManager': 'Executar Release do Gestor',
  'release.executeInstaller': 'Executar Release do Gestor Instalador',
  'release.notPrepared': 'Execute Preparar Release antes da fase de execução.',
  'release.coreMissing': 'O repositório Conn2Flow Core não foi encontrado.',
  'release.cleanTree': 'Árvore de trabalho limpa',
  'release.docsReady': '{count} arquivos de documentação de release conferidos e sincronizados',
  'release.docsBlocked': 'A documentação requer atenção: {issues}',
  'release.prepareTitle': 'Preparar Release do {product}',
  'release.prepareDescription': 'A Fase 1 coleta diagnósticos e salva um rascunho editável sem alterar o repositório.',
  'release.prepareImpact': 'A execução permanece travada até passarem os gates de permissão, Git, tag, workflow e documentação.',
  'release.saveDraft': 'Salvar Preparação',
  'release.branch': 'Branch atual',
  'release.permission': 'Permissão no GitHub',
  'release.modifiedFiles': 'Arquivos modificados',
  'release.documentation': 'Documentação pré-release',
  'release.releaseNotes': 'Rascunho das notas de release',
  'release.draftSaved': 'Rascunho de release salvo no estado do workspace.',
  'release.executeReady': 'A Fase 2 está pronta.',
  'release.executionBlocked': 'A Fase 2 está travada: {blockers}',
  'release.openPreparation': 'Abrir Preparação',
  'release.openScm': 'Controle de Código-Fonte',
  'release.blocker.workspace-untrusted': 'o workspace não é confiável',
  'release.blocker.permission-denied': 'a permissão de release no GitHub foi negada',
  'release.blocker.permission-unknown': 'não foi possível verificar a permissão de release no GitHub',
  'release.blocker.dirty-tree': 'a árvore de trabalho possui alterações não commitadas',
  'release.blocker.detached-head': 'o Git está em estado detached HEAD',
  'release.blocker.non-github-remote': 'o origin não aponta para um repositório GitHub',
  'release.blocker.tag-collision': 'a tag calculada já existe',
  'release.blocker.documentation-outdated': 'a documentação de release está ausente ou desatualizada',
  'release.blocker.draft-missing': 'o rascunho de preparação do release está ausente',
  'release.blocker.required-file-missing': 'um arquivo obrigatório do release está ausente',
  'release.blocker.workflow-busy': 'o workflow de release já está em execução',
  'release.workflowMissing': 'A execução do GitHub Actions não foi encontrada.',
  'agents.hubWatcherActive': '🟢 Watcher da Tríade: ATIVO (Ouvindo MCP Hub)',
  'agents.hubWatcherPaused': '⚪ Watcher da Tríade: PAUSADO',
  'hub.taskDispatched': 'Conn2Flow: Executando {req}…',
  'hub.executorCompleted': 'Conn2Flow: Recibo do Executor emitido para {batch}. Pronto para Revisão!',
  'hub.watcherStarted': 'Watcher da Tríade ativado.',
  'hub.watcherPaused': 'Watcher da Tríade pausado.',
  'release.saveAndExecute': 'Salvar e Executar Release',
  'release.executing': 'Executando release…',
  'release.progress': 'Executando release de {product}',
  'release.workflowProgress': 'Aguardando workflow de {product}',
  'release.preparingFeedback': 'Preparando Release do {product}…',
  'common.loading': 'Carregando…',
  'tooltip.section.overview': 'Defina o escopo SDD, projeto alvo, idioma, modo de agentes e estado do watcher antes de iniciar o trabalho. Essas escolhas são persistidas neste workspace.',
  'tooltip.section.sdd': 'Navegue pelos registros SDD governados e coordene o trabalho do executor pelo escopo ativo. Abrir documentos não modifica seu conteúdo.',
  'tooltip.section.core': 'Execute manutenção do Core e prepare releases protegidos. A execução do release fica bloqueada até os gates de preflight passarem.',
  'tooltip.section.projects': 'Selecione e opere um projeto satélite no ambiente local de testes. Os comandos usam explicitamente o alvo selecionado.',
  'tooltip.section.diagnostics': 'Inspecione serviços locais, logs e consistência dos kits de IA ao diagnosticar o ambiente de desenvolvimento. O acompanhamento de logs pode ser interrompido no mesmo controle.',
  'tooltip.section.agents': 'Abra os manuais operacionais do Dev Tools, CLI, fluxo SDD, arquitetura de agentes e skills. Estes links apenas navegam pela documentação.',
  'tooltip.section.custom': 'Execute ações definidas pelo projeto no manifesto local. Os comandos ficam indisponíveis até o workspace ser confiável.',
  'tooltip.overview.scope': 'Escolha qual diretório SDD de repositório o painel consulta. Use antes de abrir requisições ou validações para não atuar em outro projeto.',
  'tooltip.overview.target': 'Altere o alvo explícito dos comandos contextuais de projeto. Isso não executa atualização ou deploy sozinho.',
  'tooltip.overview.noTarget': 'Escolha um projeto antes de usar ações contextuais. Nenhum pipeline é iniciado até um alvo válido ser selecionado.',
  'tooltip.overview.language': 'Escolha o idioma de runtime dos rótulos e formulários. Títulos estáticos da Paleta de Comandos podem exigir recarregar o VS Code.',
  'tooltip.overview.topology': 'Escolha o modelo de colaboração de duplo agente ou tríade. A seleção molda os prompts de agentes gerados neste workspace.',
  'tooltip.overview.autonomy': 'Escolha o modo supervisionado, monitorado ou headless. O modo selecionado é encaminhado ao fluxo governado de agentes.',
  'tooltip.sdd.selectScope': 'Selecione o repositório cujos registros SDD serão consultados. Use quando o workspace contiver mais de um projeto governado.',
  'tooltip.sdd.viewMode': 'Alterne documentos Markdown entre preview, fonte e lado a lado. Isso apenas muda a apresentação no editor.',
  'tooltip.sdd.openCurrent': 'Abra o ponteiro da requisição ativa para o escopo SDD selecionado. Use para confirmar o trabalho aprovado antes de implementar.',
  'tooltip.sdd.openSpec': 'Abra a especificação normativa do escopo selecionado. Consulte-a antes de mudar contratos ou critérios de aceite.',
  'tooltip.sdd.openChecklist': 'Abra o checklist de validação em que as evidências executáveis são registradas. Use durante a verificação do batch atual.',
  'tooltip.sdd.browseRequests': 'Navegue pelas requisições humanas formais do escopo selecionado. Ideias de backlog continuam não executáveis até serem promovidas aqui.',
  'tooltip.sdd.browseBatches': 'Navegue por registros operacionais de batch e seus status. Use para retomar o batch ativo sem duplicar trabalho.',
  'tooltip.sdd.browseBacklog': 'Navegue por ideias SDD incubadas e seus status. Esta visualização nunca inicia implementação diretamente de um item de backlog.',
  'tooltip.sdd.browseDecisions': 'Navegue por decisões arquiteturais aprovadas do escopo atual. Use para manter a implementação local alinhada à governança.',
  'tooltip.sdd.browseHandoffs': 'Navegue pelos handoffs de agentes que registram o contexto de execução. Use para coordenar revisão sem alterar o histórico Git.',
  'tooltip.sdd.autoGardening': 'Monitore o alerta de 50 KB / 200 linhas e o teto de poda de 75 KB / 300 linhas. Memórias saudáveis nunca são reescritas automaticamente.',
  'tooltip.sdd.runGardening': 'Valide a memória de execução selecionada contra o alerta de 50 KB e o teto de 75 KB. É proibido podar arquivos saudáveis abaixo do alerta.',
  'tooltip.sdd.createGardening': 'Prepare uma requisição formal de gardening em vez de editar registros governados ad hoc. Revise e aprove a requisição antes da implementação.',
  'tooltip.core.updateAll': 'Execute o pipeline oficial local de atualização do Core. Use para sincronizar o sistema de testes por suas etapas protegidas.',
  'tooltip.core.syncResources': 'Compile e sincronize recursos de autoria pela esteira oficial. Use após alterar entradas de recursos, nunca como cópia manual de arquivos.',
  'tooltip.core.cssRebuild': 'Reconstrua o CSS derivado para o projeto selecionado. Use após alterar templates ou recursos dependentes de Tailwind.',
  'tooltip.core.cssAudit': 'Inspecione origem e cobertura do CSS no projeto selecionado. Use para diagnosticar estilos gerados desatualizados ou não reconhecidos.',
  'tooltip.release.verify': 'Verifique autenticação GitHub e permissão de release antes de prepará-lo. Isso não modifica o repositório nem publica nada.',
  'tooltip.release.manager': 'Inicie a fase 1 do fluxo de release do Gestor e salve um rascunho editável. Nenhum commit, tag ou ação remota ocorre nesta fase.',
  'tooltip.release.installer': 'Inicie a fase 1 do release do Gestor Instalador e salve um rascunho editável. Ele permanece local até a fase 2 passar por todos os gates.',
  'tooltip.release.executeManager': 'Execute a fase 2 de um release preparado do Gestor somente após todas as verificações locais e de permissão. Isso pode criar efeitos remotos no Git e GitHub.',
  'tooltip.release.executeInstaller': 'Execute a fase 2 de um release preparado do Gestor Instalador somente após todas as verificações locais e de permissão. Isso pode criar efeitos remotos no Git e GitHub.',
  'tooltip.release.openActions': 'Abra o GitHub Actions para inspecionar o workflow associado a um release permitido. Isso não dispara novo workflow.',
  'tooltip.projects.setTarget': 'Selecione o projeto usado pelos comandos contextuais. Escolher um alvo apenas altera o estado do workspace.',
  'tooltip.projects.updateAll': 'Execute o pipeline oficial completo do projeto selecionado em seu ambiente de testes. Use após mudanças coordenadas no Core ou projeto.',
  'tooltip.projects.syncCore': 'Sincronize a camada Core ao projeto selecionado pela esteira aprovada. Use antes de validar a integração do projeto.',
  'tooltip.projects.syncFiles': 'Sincronize arquivos do projeto ao ambiente local de testes pela tarefa oficial. Não use cópias manuais em espelhos.',
  'tooltip.projects.deploy': 'Faça deploy do projeto selecionado pelo fluxo configurado. Revise o alvo e o formulário de confirmação antes de continuar.',
  'tooltip.projects.updateSelect': 'Escolha outro projeto e execute seu pipeline completo de atualização. Use quando o alvo atual deve permanecer inalterado.',
  'tooltip.projects.deploySelect': 'Escolha um projeto para deploy sem alterar o alvo padrão. Confirme o impacto remoto no formulário apresentado.',
  'tooltip.projects.scaffold': 'Crie a estrutura padrão de um novo projeto satélite. Use somente ao iniciar um projeto gerenciado separadamente.',
  'tooltip.projects.register': 'Cadastre um projeto existente na configuração de ambiente. Isso o disponibiliza para comandos explícitos de projeto.',
  'tooltip.projects.clone': 'Clone repositórios configurados que estiverem ausentes ao lado do workspace. Use para reparar um checkout local incompleto.',
  'tooltip.projects.syncTemplate': 'Sincronize a configuração de ambiente ativa com o template do Core. Revise a configuração resultante antes de operar projetos.',
  'tooltip.diagnostics.dockerStatus': 'Mostre a saúde e o estado dos containers Docker locais. Use antes de diagnosticar serviços que dependem da stack de desenvolvimento.',
  'tooltip.diagnostics.apacheLogs': 'Inicie ou pare o acompanhamento dos logs Apache em terminal dedicado. Use ao reproduzir problemas HTTP ou de rota localmente.',
  'tooltip.diagnostics.phpLogs': 'Inicie ou pare o acompanhamento dos logs PHP em terminal dedicado. Use ao reproduzir erros do lado do servidor localmente.',
  'tooltip.diagnostics.truncatePhp': 'Limpe o log de erros PHP local após revisá-lo. Use para isolar uma nova reprodução, pois as evidências anteriores serão removidas.',
  'tooltip.diagnostics.aiSync': 'Valide os contratos dos kits de IA e seu estado de sincronização. Use após mudar instruções, skills ou definições de agentes compartilhadas.',
  'tooltip.diagnostics.syncAll': 'Execute o fluxo configurado de distribuição de skills entre repositórios. Revise os repositórios alvo antes de iniciar a tarefa.',
  'tooltip.docs.panel': 'Abra o Manual do Painel Dev Tools v2. Use para entender a árvore, controles, fases de release, watcher e ações SDD integradas.',
  'tooltip.docs.cli': 'Abra o guia rápido de CLI e MCP. Use para encontrar comandos oficiais, configuração do Hub MCP e fluxos locais suportados.',
  'tooltip.docs.orchestration': 'Abra o playbook de orquestração multiagente. Use para coordenar handoffs entre arquiteto, executor, revisor e MCP.',
  'tooltip.docs.architecture': 'Abra o guia de arquitetura de duplo agente e tríade. Use para escolher responsabilidades e autonomia de uma tarefa governada.',
  'tooltip.docs.skills': 'Abra o catálogo de skills de framework e SDD disponíveis. Use para identificar a orientação operacional exigida antes de uma tarefa.',
  'tooltip.docs.index': 'Abra o índice bilíngue de documentações. Use-o para navegar por todos os guias mantidos no catálogo autoritativo do workspace.',
  'tooltip.docs.roadmap': 'Abra o roteiro de evolução futura. Use-o para conhecer capacidades planejadas sem tratar itens de backlog como contratos implementados.',
  'tooltip.agents.hubWatcherActive': 'Pause o watcher de tarefas do Hub MCP quando notificações automáticas precisarem ficar silenciosas. Reative-o para receber atualizações novamente.',
  'tooltip.agents.hubWatcherPaused': 'Ative o watcher de tarefas do Hub MCP para receber atualizações de despacho e recibos do executor. Ele observa o Hub sem executar uma tarefa.',
  'tooltip.agents.launchClaude': 'Inicie o fluxo aprovado do executor com o contexto SDD gerado. Use após confirmar a requisição ativa e seu modo de autonomia.',
  'tooltip.agents.copyPrompt': 'Copie um prompt completo de executor com o repositório alvo e requisição ativa. Use para encaminhar trabalho a um agente suportado manualmente.',
  'tooltip.agents.recordHandoff': 'Abra o handoff atual do executor para o escopo selecionado. Registre nele decisões e evidências de validação para o próximo revisor.',
  'tooltip.agents.prepareReview': 'Abra o handoff atual e foque o Controle de Código-Fonte para revisão do arquiteto. Isso não faz commit, push ou publicação.',
  'tooltip.custom.edit': 'Abra o manifesto de ações do projeto para edição deliberada. Use para definir ações locais antes de elas aparecerem nesta seção.',
  'tooltip.custom.action': 'Execute esta ação pelo manifesto confiável do projeto. Revise o comando ou arquivo configurado antes de continuar.'
};

export function resolveLocale(
  preference: LanguagePreference,
  vscodeLanguage: string,
  environmentLanguage?: string
): SupportedLocale {
  if (preference === 'pt-BR' || preference === 'en') {
    return preference;
  }

  const normalizedVscode = vscodeLanguage.trim().toLocaleLowerCase('en-US');
  if (normalizedVscode === 'pt' || normalizedVscode.startsWith('pt-')) {
    return 'pt-BR';
  }
  if (normalizedVscode === 'en' || normalizedVscode.startsWith('en-')) {
    return 'en';
  }

  const normalizedEnvironment = (environmentLanguage || '').trim().toLocaleLowerCase('en-US');
  if (normalizedEnvironment === 'pt' || normalizedEnvironment === 'pt-br') {
    return 'pt-BR';
  }
  return 'en';
}

export function translate(
  locale: SupportedLocale,
  key: TranslationKey,
  values: Readonly<Record<string, string | number | boolean>> = {}
): string {
  const catalog = locale === 'pt-BR' ? ptBR : en;
  return catalog[key].replace(/\{([a-zA-Z0-9_]+)\}/g, (match, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : match
  );
}
